services:
  api:
    build: .
    container_name: adbrew_api
    command: bash -c "cd /src/rest && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ${ADBREW_CODEBASE_PATH}/tmp:/tmp
      - ${ADBREW_CODEBASE_PATH}:/src
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

  app:
    build: .
    container_name: adbrew_app
    command: bash -c "cd /src/app && yarn install && yarn start"
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ${ADBREW_CODEBASE_PATH}:/src

  mongo:
    image: mongo:4.4
    container_name: adbrew_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${ADBREW_CODEBASE_PATH}/db/:/data/db
    # default command from the mongo image is fine; no custom command needed
